sudo: required
services:
  - docker

before_install:
  - docker build -t rachitsxn292/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rachitsxn292/react-test npm test

after_success:
  - docker build -t rachitsxn292/multi-client ./client 
  - docker build -t rachitsxn292/multi-nginx ./nginx 
  - docker build -t rachitsxn292/multi-server ./server 
  - docker build -t rachitsxn292/multi-worker ./worker 
  #log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those image and push them to docker hub
  #Fuck Ya all nigga
 - docker push rachitsxn292/multi-client
 - docker push rachitsxn292/multi-nginx
 - docker push rachitsxn292/multi-server
 - docker push rachitsxn292/multi-worker
